### ISSUE TITLE
Problem with pywdf installation " python setup.py egg_info did not run successfully"

### ISSUE THREAD

**Issue by Cristiano1997** [gusanthon/pywdf#3]
###  Hello, i try to install pywdf, but i can't, i have this error:

(.venv) PS C:\Users\Cristiano\PycharmProjects\ProvaPYTHON> pip install git+https://github.com/gusanthon/pywdf
Collecting git+https://github.com/gusanthon/pywdf
  Cloning https://github.com/gusanthon/pywdf to c:\users\cristiano\appdata\local\temp\pip-req-build-vduvqfxm
  Running command git clone --filter=blob:none --quiet https://github.com/gusanthon/pywdf 'C:\Users\Cristiano\AppData\Local\Temp\pip-req-build-vduvqfxm'
  Resolved https://github.com/gusanthon/pywdf to commit f4c1df0bb9d245c26db68c339bb84ad211dafd44
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Cristiano\AppData\Local\Temp\pip-req-build-vduvqfxm\setup.py", line 4, in <module>
          long_description = fh.read()
                             ^^^^^^^^^
      UnicodeDecodeError: 'cp932' codec can't decode byte 0x82 in position 1181: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### I use Python 3.12.3  , pip 24.0 on Windows 10;
How can I solve it?
Thanks for you attention

**Comment by xaviliz** [comment]
Hi Cristiano,

Sorry, it has been only tested on Linux and OSX, never on Windows. 
Maybe you can try with WSL: https://learn.microsoft.com/en-us/windows/wsl/install
Hope this helps.
